spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:demo_test;MODE=MYSQL
  jpa:
    hibernate:
      ddl-auto: create
custom:
  tempDirPath: c:/gamedragons/gamedragons_test/temp
  genFile:
    dirPath: c:/gamedragons/demo_test