name: workflow-server-1
on:
  push: # 해당 경로의 파일이 변경되었을 때만 워크플로우가 실행
    paths:
      - '.github/workflows/**'
      # back
      - 'src/**'
      - 'build.gradle'
      - 'Dockerfile'
    branches:
      - main
jobs:
  makeTagAndRelease:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.create_tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Create Tag
        id: create_tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.new_tag }}
          release_name: Release ${{ steps.create_tag.outputs.new_tag }}
          body: ${{ steps.create_tag.outputs.changelog }}
          draft: false
          prerelease: false
  buildImageAndPush:
    permissions: #403 error 해결 위한 explicit permission 추가
      contents: read
      packages: write
    name: 도커 이미지 빌드와 푸시
    needs: makeTagAndRelease
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Buildx 설치
        uses: docker/setup-buildx-action@v2
      - name: 레지스트리 로그인
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: username 대문자 소문자로 변환
        run: |
          echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - name: application-secret.properties 생성
        env:
          ACTIONS_STEP_DEBUG: true
          APPLICATION_SECRET: ${{ secrets.APPLICATION_SECRET_PROPERTIES }}
        run: echo "$APPLICATION_SECRET" > ./src/main/resources/application-secret.yml
      - name: 빌드 앤 푸시(Server)
        uses: docker/build-push-action@v3
        with:
          # 빌드시 사용할 도커파일 경로와 컨텍스트 지정
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/gamedragons-server-deploy:${{ needs.makeTagAndRelease.outputs.tag_name }},
            ghcr.io/${{ env.OWNER_LC }}/gamedragons-server-deploy:latest
